FROM centos:latest

RUN mkdir /opt/tomcat/
WORKDIR /opt/tomcat
ADD  https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz .
   RUN tar xvfz apache*.tar.gz \
   && mv apache-tomcat-9.0.40/* /opt/tomcat/ \
   && yum -y install java \
   && java -version

WORKDIR /opt/tomcat/webapps
COPY target/*.war/opt/tomcat

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
